### ISSUE TITLE
Cities in country page

### ISSUE THREAD

**Issue by oesukam** [devscast/covid19-client#10]
**Describe the bug**

The country page is listing countries and cities. I think we should only display countries 

**To Reproduce**

1. Navigate to [Countries](https://covid-19info.cd/countries)
2. Search for `China`
3. See a list of impacted cities instead of china a whole

**Expected behavior**

- I expect to only see the country when searching for one but the API is returning by cities for some countries

**Screenshots**

**Desktop (please complete the following information):**
 
![image](https://user-images.githubusercontent.com/17350127/77625117-aafa9280-6f4b-11ea-8608-88b4812b844f.png)

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by bernard-ng** [comment]
yes, in principle it should be "regions", the JHU api provides data according to regions infected by countries. so either we'll have to "map - reduce" the result of the api to display them by country, or we send all this logic back to the backend and use a single data source. what do you think?

**Comment by oesukam** [comment]
@bernard-ng We can use a quick fix for now in the frontend with array manipulation and maybe later implement it in the backend.
I was also thinking of moving the API to the backend so that the backend updates data maybe after every 5 to 10 minutes

**Comment by bernard-ng** [comment]
All right, you can get started, and I'll start preparing the backend.

**Comment by bernard-ng** [comment]
All right, you can get started, and I'll start preparing the backend.
