### ISSUE TITLE
Missing information from the API

### ISSUE THREAD

**Issue by oesukam** [devscast/covid19-client#12]
**Describe the bug**

The API returns some countries without `iso2`, `iso3`, etc.
An example can be found below for DRC
```json
{
"provinceState": null,
"countryRegion": "Congo (Kinshasa)",
"lastUpdate": 1585231064000,
"lat": -4.322447,
"long": 15.307045,
"confirmed": 51,
"recovered": 0,
"deaths": 3,
"active": 48,
"admin2": null,
"fips": null,
"combinedKey": "Congo (Kinshasa)",
"incidentRate": null,
"peopleTested": null,
"url": "congo%20(kinshasa)--15.307045---4.322447"
}
```

**To Reproduce**

- Look for Congo
- See the country on the list without the flag

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 

**Additional context**

**Comment by bernard-ng** [comment]
yes, but this is JHU's api which has a problem, I've already started to work on unifying all the data on our backend.
