### ISSUE TITLE
Ajout d'un nouveau menu "Évaluation"  ou " Test rapide" ou un autre terme... 

### ISSUE THREAD

**Issue by lubangi** [devscast/covid19-client#18]
je travaille sur la traduction d'une app de diagnostique automatique que l'on va ajouter dans le projet en 5 langues ( français et 4 langues nationales), la version française est disponible en pièce jointe:  
[feature_covid-19.zip](https://github.com/devscast/covid19-backend/files/4416283/feature_covid-19.zip)

**Comment by bernard-ng** [comment]
@lubangi salut, nous apprécions l'initiative, ceci dit il y a quelque points à corriger afin de faciliter l'integration dans l'application existante.

1. le frontend est fait avec le framework angular, je vous demanderai d'adapter votre code à celui. 

2. Nous Utilisons Tailwindcss comme framework CSS, je vous demanderai d'adapter aussi votre interface avec ce framework pour garder une coherence dans notre design system.

3. Pour ce qui est des images, des version SVG plutôt que PNG seraient la bienvenue (ceci est optionnel).

**Comment by bernard-ng** [comment]
aussi vous pouvez directement contribuer au code, plutôt qu'indexer des pièces jointes et nous demander de les intégrer à votre place. merci.

**Comment by lubangi** [comment]
Merci, mais lorsque j'ai demandé dans le groupe Whatsapp, comment intégrer cette app, on m'a dit que comme c'est une page Web codé en js son intégration ne posera aucun problème sur l'application web tout d'abord.

**Comment by bernard-ng** [comment]
J'avais pas vu votre message, sinon je vous aurez informé des aspects techniques nécessaires.
