### ISSUE TITLE
Add country's pagination

### ISSUE THREAD

**Issue by oesukam** [devscast/covid19-client#2]
**Is your feature request related to a problem? Please describe.**
Listing all countries doesn't give a good user experience even if there is a search bar
Page: https://covid-19info.cd/countries

**Describe the solution you'd like**
- It will be better to include pagination and filters per continent and regions if possible
- Also having a possibility to sort countries by differents information such as the most affected, having active cases, recovered and so on

**Describe alternatives you've considered**
- N/A

**Additional context**
- N/A

**Comment by oesukam** [comment]
@bernard-ng It seems there is already someone working on this. Please check [PR 6](https://github.com/devscast/covid19-client/pull/6) from @masterDev32

**Comment by oesukam** [comment]
@bernard-ng I can maybe start working on the language translation if no one is working on it already

**Comment by bernard-ng** [comment]
yeah, i just saw his work
